
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spree_development
  username: joker
  password: joker
  timeout: 5000

test:
  <<: *default
  database: spree_test
  username: joker
  password: joker
  timeout: 5000

production:
  <<: *default
  database: spree
  username: joker
  password: joker
